### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by CollenMenezes** [daprofiler/DaProfiler#11]
No module named 'hub'

How to solve it?

**Comment by Sn0wAlice** [comment]
daprofiler is depreciated for the moment. please wait the next update

**Comment by CollenMenezes** [comment]
> daprofiler is depreciated for the moment. please wait the next update

Oh, sure.

**Comment by CollenMenezes** [comment]
> I can't fix it rn, delete the line 48 in profiler.py

Now I got this.

NameError: name 'write' is not defined

**Comment by Sn0wAlice** [comment]
@TheRealDalunacrobate i'am serrious when a told him to wait the next update, THIS ONE IS FUCKING ERRORED
