### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by imvast** [daprofiler/DaProfiler#16]
1. use httpx instead of requests it works the same but is much faster
2. fix the bug showing "cannot import last_diplomes.py from modules" -- its a simple fix just add the "last_diplomes.py" file into /modules
3. add more and automatic api implementation instead of having users get there own

**Comment by Sn0wAlice** [comment]
this is why github invented the pull request 👍

**Comment by balluh** [comment]
can u send proof of httpx being faster?

**Comment by balluh** [comment]
also, GitHub did not invent the pull request

**Comment by TheRealDalunacrobate** [comment]
>     2. fix the bug showing "cannot import last_diplomes.py from modules" -- its a simple fix just add the "last_diplomes.py" file into /modules> 

Fixed.
