### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by Liweyz** [daprofiler/DaProfiler#17]
Bonjour, j'ai un soucis quand je lance les requirements tous fonctionne et dès que je lance la commande py profiler.py -h ça me met ceci merci

Traceback (most recent call last):
  File "C:\Users\mikou\Desktop\DaProfiler-main\profiler.py", line 1, in <module>
    from colorama.initialise import init
ModuleNotFoundError: No module named 'colorama'

cordialement Liweyz

**Comment by Liweyz** [comment]
oui ça met ceci 
Requirement already satisfied: colorama in c:\users\mikou\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (0.4.5)

**Comment by 3xpl0it-Sh4d0w** [comment]
Ok donc à présent `colorama` est installé,
Vous avez essayé de ré exécuter `DaProfiler` ?

**Comment by Liweyz** [comment]
Oui j'ai exécuté py profiler.py -h  mes  ça met toujours ceci je ne comprend pas 

C:\Users\mikou\Desktop\DaProfiler-main>py profiler.py -h
Traceback (most recent call last):
  File "C:\Users\mikou\Desktop\DaProfiler-main\profiler.py", line 1, in <module>
    from colorama.initialise import init
ModuleNotFoundError: No module named 'colorama'

**Comment by TheRealDalunacrobate** [comment]
pip uninstall colorama && pip3 install colorama
