### ISSUE TITLE
profiler.py: command not found

### ISSUE THREAD

**Issue by CookSavon** [daprofiler/DaProfiler#19]
Hello, sorry for this post i"m an absolute noob and i use osint tools in google cloud shell. I correctly cloned the repo but when i try to use it, it doesn't work.

![image](https://user-images.githubusercontent.com/89949987/197701605-f0ab4e94-3be4-4619-85a3-0c4ed6ddf818.png)

Even if try something like profiler.py -n NAME -ln NAME etc... the command is not found in all cases (and yeah i indeed did cd DaProfiler so i'm in the correct directory)

Thanks in advance for you patience.

**Comment by Sn0wAlice** [comment]
profiler.py is a python script. so:

`python3 profiler.py -n NAME -ln LASTNAME`

**Comment by CookSavon** [comment]
Thanks it work well now
