### ISSUE TITLE
ImportError with Soundclound library

### ISSUE THREAD

**Issue by Sklyvan** [daprofiler/DaProfiler#20]
**Describe the bug**
Problem with the soundclound library. 
```python
ImportError: cannot import name 'soundclound' from 'modules' (unknown location)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. pip install -r requirements.txt
2. python3 profiler.py

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11
 - Browser: Firefox
 - Version: 102.4.0esr

**Comment by TheRealDalunacrobate** [comment]
Fixed.
