### ISSUE TITLE
Name of the city is truncated 

### ISSUE THREAD

**Issue by ThierryGuegan** [daprofiler/DaProfiler#22]
Fix : 
        tree.create_node('{} | {}\t| {}'.format(i['Age'],i['Name'],i['Loc']),parent=41518181871541514778)

1st letter of the city waq truncated in the tree view

**Comment by TheRealDalunacrobate** [comment]
Hi Thierry, can you send me the city name please ? Here is my mail adress : **[daluna_pro@protonmail.ch](url)**

**Comment by ThierryGuegan** [comment]
For example, as shown in the attached screenshot : 
 
Amiens (80) is truncated and become miens (80) 
Caen( 14) become aen (14) 

![image](https://user-images.githubusercontent.com/23701691/206860068-9debbda5-b47d-4ba4-a78e-2a8d30ae7141.png)

**Comment by TheRealDalunacrobate** [comment]
Fixed.
