### ISSUE TITLE
bfmtv_search is only returning the 1st line 

### ISSUE THREAD

**Issue by ThierryGuegan** [daprofiler/DaProfiler#24]
bfmtv_search is only returning the 1st line 

It should loop for all the lines

**Comment by TheRealDalunacrobate** [comment]
Please add more details to the issue

**Comment by ThierryGuegan** [comment]
If I use the URL written in the code of dirigeants_bfmtv.py 
I get : 

![image](https://user-images.githubusercontent.com/23701691/206860256-efb40c12-6f95-466d-8baf-ef74b2c0981c.png)


But if I run the program, only the 1st line is returned (the one with "22 mandats") 

![image](https://user-images.githubusercontent.com/23701691/206860280-8480409d-5894-4940-a0ca-c5d9fb713e0a.png)

**Comment by TheRealDalunacrobate** [comment]
Yeah it's normal man, I don't want to show all the results
