### ISSUE TITLE
Problem when loading cmd for the requirement.txt

### ISSUE THREAD

**Issue by HermesOne** [daprofiler/DaProfiler#28]
Hi,

when i'm trying to download the requirement text, the terminal in sending me as a response : 

ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2 

Any Ideas? 

Great job btw

Kind regards all,

Fyi : 

already try :

pip install opencv-python
pip uninstall opencv-pyton
pip3 install opencv-python

**Comment by HermesOne** [comment]
already try : 

pip install opencv-python
pip uninstall opencv-pyton
pip3 uninstall opencv-python

**Comment by crispyabsurdist** [comment]
Remove cv2 and add opencv-python instead. you can also remove io.

**Comment by HermesOne** [comment]
Hi, 

I'm a beginner in terms of using this kind of tools/python cmd, 

could you give me more informations about the cmd to execute ? 

Thank's

**Comment by ViklandHA** [comment]
Hi, 
You have to modify requirements.txt
with 
$ sudo nano requirements.txt
then change cv2 by opencv-python 
and remove io
Then Ctrl+O to save the file and Ctrl+X to quit nano

**Comment by HermesOne** [comment]
Ok Thx so much

**Comment by HermesOne** [comment]
Last question haha, 

Go to [modules\linkedin_search] then add your creditentials.

I did not succeed this step, 

Thank's again
