### ISSUE TITLE
Stuck on mailbox guessing

### ISSUE THREAD

**Issue by nezlok** [daprofiler/DaProfiler#33]
isitarealemail shows it's checking mails, but then it appears to get stuck.  The skype check website is throwing 500s, is it possible this is an exception not caught?

**Comment by TheRealDalunacrobate** [comment]
> isitarealemail shows it's checking mails, but then it appears to get stuck. The skype check website is throwing 500s, is it possible this is an exception not caught?

Hi ! It was a timeout error, Fixed now. Thanks you !
