### ISSUE TITLE
socketio.Client() error

### ISSUE THREAD

**Issue by black-syphilis** [daprofiler/DaProfiler#6]
If you have an error about socketio.Client() try to install python-socketio

**Comment by Machou** [comment]
I have install socketIO with ```apt install python3-socketio-client python3-socketio```

But i have this error :

```
ERROR: Could not find a version that satisfies the requirement string
ERROR: No matching distribution found for string
```

**Comment by Sn0wAlice** [comment]
User pip install and not apt

**Comment by Machou** [comment]
I have try with pip, first, but don't worked.

It's hardly bugged.

**Comment by Sn0wAlice** [comment]
no longer supported in Daprofiler v2
